joke/spock-mockable

.github/autoapproval.yml
.github/settings.yml

- chore: settings
- chore: add auto approval bot

chore: settings

---

spock-mockable/src/main/java/io/github/joke/spockmockable/internal/MockableExtension.java

fix: exception during processing of classes with unknown type

---

.github/workflows/release.yml
build.gradle

ci: fix release-please workflow

---

spock-mockable/src/main/java/io/github/joke/spockmockable/internal/MockableExtension.java

fix: improve debug logging

---

examples/spock/build.gradle

refactor(gradle): switch from jvm test suite to regular tests

---

spock-mockable/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/internal/EngineDiscovery.java
spock-mockable/src/main/java/io/github/joke/spockmockable/internal/MockableTransformer.java
spock-mockable/src/main/java/io/github/joke/spockmockable/internal/hooks/GlobalExtension.java
spock-mockable/src/main/java/io/github/joke/spockmockable/internal/hooks/TestExecution.java
spock-mockable/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension

fix: earlier junit startup if possible

---

.github/dependabot.yml

ci(dependabot): ignore problematic versions

---

build.gradle

ci: switch versioning plugin

---

README.adoc
examples/kotlin/build.gradle
examples/spock/build.gradle
examples/spring/build.gradle
spock-mockable/build.gradle

chore: spock 2.3 support

---

.github/settings.yml
.github/workflows/codeql-analysis.yml

ci: codeql scanning

---

.github/workflows/codeql-analysis.yml

ci: fix codeql scanning

---

README.adoc
examples/spock/build.gradle

refactor!: drop support for spock 1.3

---

.github/workflows/build.yml
.github/workflows/release.yml
build.gradle
examples/spock/build.gradle

ci: update gradle project setup

---

.github/workflows/build.yml
build.gradle
spock-mockable/build.gradle

ci: codecov integration

---

README.adoc

docs: moved table of content

---

README.adoc
spock-mockable/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/AgentInstaller.java

feat: support earlier transformation as -javaagent

---

spock-mockable/src/main/java/io/github/joke/spockmockable/agent/AgentInstaller.java

fix: agent deactivation via system property

---

dependencies/build.gradle
spock-mockable/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/RedefinitionListener.java
spock-mockable/src/test/groovy/io/github/joke/spockmockable/agent/RedefinitionListenerTest.groovy

chore: basic unit testing setup

---

README.adoc
dependencies/build.gradle
examples/kotlin/build.gradle
examples/spock/build.gradle
examples/spring/build.gradle

chore: correct test dependency versions

---

spock-mockable/build.gradle

fix: publishing shadow artifact closes #269

---

README.adoc

docs: improve documentation

---

dependencies/build.gradle
spock-mockable/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/ast/SourceUnitProcessor.java
spock-mockable/src/test/groovy/io/github/joke/spockmockable/ast/ClassCollectorTest.groovy
spock-mockable/src/test/groovy/io/github/joke/spockmockable/ast/SourceUnitProcessorTest.groovy

chore: increase test coverage

---

examples/spock/build.gradle

ci: fix test execution

---

build.gradle
spock-mockable/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/ClassTransformer.java
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/StaticMockHandler.java
spock-mockable/src/main/java/io/github/joke/spockmockable/hooks/StaticMockExtension.java

test: improve testing

---

dependencies/build.gradle
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/PropertyReader.java
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/ReferenceLoader.java
spock-mockable/src/test/groovy/io/github/joke/spockmockable/agent/ReferenceLoaderTest.groovy
spock-mockable/src/test/groovy/io/github/joke/spockmockable/agent/TransformationStarterTest.groovy

test: increase test coverage

---

.github/workflows/build.yml
examples/spock/build.gradle
examples/spock/src/main/java/io/github/joke/examples/Person.java
examples/spock/src/main/java/io/github/joke/examples/StaticCaller.java
examples/spock/src/main/java/io/github/joke/examples/Utility.java
examples/spock/src/test/groovy/io/github/joke/examples/MockTest.groovy
examples/spock/src/test/groovy/io/github/joke/examples/MockableClassTest.groovy
examples/spock/src/test/groovy/io/github/joke/examples/MockablePackageTest.groovy
examples/spock/src/test/groovy/io/github/joke/examples/SpyTest.groovy
examples/spock/src/test/groovy/io/github/joke/examples/StaticTest.groovy
examples/spock/src/test/groovy/io/github/joke/examples/StubTest.groovy

build: coverage for integration tests

---

.github/workflows/build.yml
.github/workflows/release.yml

ci: use gradle build action

---

.github/workflows/codeql-analysis.yml

ci: use gradle build action in codeql

---

spock-mockable/src/main/java/io/github/joke/spockmockable/agent/ClassTransformer.java
spock-mockable/src/main/java/io/github/joke/spockmockable/agent/DiscoveryListener.java
spock-mockable/src/test/groovy/io/github/joke/spockmockable/agent/ClassTransformerTest.groovy

feat: improve transformation logging

---

spock-mockable/build.gradle

ci: include gradle module in publication
